# Generated by Django 3.2.8 on 2021-10-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField()),
                ('name', models.CharField(default='', max_length=20)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
    ]
